sudo: required
services: docker
language: bash
env:
    global:
        - QEMU_VER=v2.11
        - DOCKER_REPO=multiarch/ubuntu-core
    matrix:
        - HOST_ARCH=ppc64le     ARCH=i386      VERSION=trusty    QEMU_ARCH=i386      TAG_ARCH=x86
        - HOST_ARCH=ppc64le     ARCH=amd64     VERSION=trusty    QEMU_ARCH=x86_64    TAG_ARCH=x86_64
        - HOST_ARCH=ppc64le     ARCH=armhf     VERSION=trusty    QEMU_ARCH=arm       TAG_ARCH=armhf
        - HOST_ARCH=ppc64le     ARCH=arm64     VERSION=trusty    QEMU_ARCH=aarch64   TAG_ARCH=arm64

        - HOST_ARCH=ppc64le     ARCH=i386      VERSION=xenial    QEMU_ARCH=i386      TAG_ARCH=x86
        - HOST_ARCH=ppc64le     ARCH=amd64     VERSION=xenial    QEMU_ARCH=x86_64    TAG_ARCH=x86_64
        - HOST_ARCH=ppc64le     ARCH=armhf     VERSION=xenial    QEMU_ARCH=arm       TAG_ARCH=armhf
        - HOST_ARCH=ppc64le     ARCH=arm64     VERSION=xenial    QEMU_ARCH=aarch64   TAG_ARCH=arm64

        - HOST_ARCH=ppc64le     ARCH=i386      VERSION=bionic    QEMU_ARCH=i386      TAG_ARCH=x86
        - HOST_ARCH=ppc64le     ARCH=amd64     VERSION=bionic    QEMU_ARCH=x86_64    TAG_ARCH=x86_64
        - HOST_ARCH=ppc64le     ARCH=armhf     VERSION=bionic    QEMU_ARCH=arm       TAG_ARCH=armhf
        - HOST_ARCH=ppc64le     ARCH=arm64     VERSION=bionic    QEMU_ARCH=aarch64   TAG_ARCH=arm64

before_script:
    - sudo apt-get -y install qemu-user-static
script:
    - sudo ./update.sh -h "$HOST_ARCH" -a "$ARCH" -v "$VERSION" -q "$QEMU_ARCH" -u "$QEMU_VER" -d "$DOCKER_REPO" -t "$TAG_ARCH"
after_success:
    - if [[ $TRAVIS_PULL_REQUEST == 'false' ]]; then docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && docker push $DOCKER_REPO; fi
